### ISSUE TITLE
Allow loading of images that aren't in MNI space

### ISSUE THREAD

**Issue by mwaskom** [neurosynth/nsviewer#13]
It's not clear to me whether the heavy lifting here is in nsviewer or XTK, but it would be good to have.

**Comment by tyarkoni** [comment]
Thanks for jogging my memory, @mwaskom... though as you can obviously tell, this project is basically dead. What are you using these days for web-based visualization? Papaya.js?

**Comment by mwaskom** [comment]
I had moved over to Papaya for the project  I'd been using nsviewer for originally, but I haven't found much use for web-based viewers lately and mostly stick with older technology (Freeview and FSLView).

**Comment by haehn** [comment]
people still use slicedrop.com and xtk pretty often :) unfortunately i have 0 time to maintain at the moment
